name       : VTK
version    : 8.1.1
release    : 5
source     :
    - https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz : 71a09b4340f0a9c58559fe946dc745ab68a866cf20636a41d97b6046cb736324
license    : BSD-3-Clause
component  : programming
summary    : Visualization toolkit
description: |
    The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, image processing, and visualization. It consists of a C++ class library and several interpreted interface layers including Tcl/Tk, Java, and Python.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xt)
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release \
        -DVTK_INSTALL_LIBRARY_DIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
