name       : VTK
version    : 8.0.1
release    : 3
source     :
    - http://www.vtk.org/files/release/8.0/VTK-8.0.1.tar.gz : 49107352923dea6de05a7b4c3906aaf98ef39c91ad81c383136e768dcf304069
license    : BSD-3-Clause
component  : programming
summary    : Visualization toolkit
description: |
    The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, image processing, and visualization. It consists of a C++ class library and several interpreted interface layers including Tcl/Tk, Java, and Python.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xt)
    - pkgconfig(x11)
setup      : |
    mkdir build
    pushd build
    %cmake .. -DCMAKE_BUILD_TYPE=Release \
              -DVTK_INSTALL_LIBRARY_DIR=%libdir%
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
