name       : VTK
version    : 9.0.3
release    : 14
source     :
    - https://www.vtk.org/files/release/9.0/VTK-9.0.3.tar.gz : bc3eb9625b2b8dbfecb6052a2ab091fc91405de4333b0ec68f3323815154ed8a
license    : BSD-3-Clause
component  : programming.library
summary    : Visualization toolkit
description: |
    The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, image processing, and visualization. It consists of a C++ class library and several interpreted interface layers including Tcl/Tk, Java, and Python.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(hdf5-1.10.4)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(liblz4)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(netcdf)
    - pkgconfig(proj)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(sqlite3)
    - pkgconfig(theora)
    - pkgconfig(x11)
    - double-conversion-devel
    # libharu-devel (needs patched version)
    - gl2ps-devel
    - utfcpp
setup      : |
    %apply_patches

    %cmake_ninja -DCMAKE_BUILD_TYPE=Release \
        -DVTK_INSTALL_LIBRARY_DIR=%libdir%/vtk \
        -DVTK_INSTALL_PACKAGE_DIR=%libdir%/cmake/vtk \
        -DVTK_INSTALL_INCLUDE_DIR=include/vtk \
        -DVTK_PYTHON_VERSION=3 \
        -DVTK_WRAP_PYTHON=ON \
        -DVTK_USE_EXTERNAL=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_libharu=OFF \
        -DVTK_MODULE_USE_EXTERNAL_VTK_pegtl=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
