name       : VTK
version    : 7.0.0
release    : 1
source     :
    - http://www.vtk.org/files/release/7.0/VTK-7.0.0.tar.gz : 78a990a15ead79cdc752e86b83cfab7dbf5b7ef51ba409db02570dbdd9ec32c3
license    : BSD-3-Clause
component  : programming
summary    : Visualization toolkit
description: |
    The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, image processing, and visualization. It consists of a C++ class library and several interpreted interface layers including Tcl/Tk, Java, and Python.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xt)
    - pkgconfig(x11)
setup      : |
    %apply_patches
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
