name       : VTK
version    : 7.1.1
release    : 2
source     :
    - http://www.vtk.org/files/release/7.1/VTK-7.1.1.tar.gz : 2d5cdd048540144d821715c718932591418bb48f5b6bb19becdae62339efa75a
license    : BSD-3-Clause
component  : programming
summary    : Visualization toolkit
description: |
    The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, image processing, and visualization. It consists of a C++ class library and several interpreted interface layers including Tcl/Tk, Java, and Python.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xt)
    - pkgconfig(x11)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
